spring:
  config:
    import: ./env/env-docker.yaml
    activate:
      on-profile: docker
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

server:
  port: 8080

frontend:
  address: http://cookie-frontend:80

jwt:
  secret: ${JWT_SECRET}