spring:
  config:
    import: ./env/env-test.yaml
    activate:
      on-profile: test
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

server:
  port: 8080

frontend:
  address: http://cookie-frontend:80

jwt:
  secret: ${JWT_SECRET}

ignore:
  matchers: >
    /api/v1/user