server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookie_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    jdbc:
#      repositories:
#        enabled: 'false'