spring:
  config:
    import: ./env/env-dev.yaml
    activate:
      on-profile: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: TRACE

config:
  frontendAddress: http://localhost:4200
  jwtSecret: ${JWT_SECRET}
  ignoreMatchers: >
    /api/v1/user,
    /api/v1/pantries,
    /api/v1/pantries/**,
    /api/v1/products,
    /api/v1/groups,
    /api/v1/groups/**,
    /api/v1/shopping-lists,
    /api/v1/shopping-lists/**,
    /api/v1/recipes,
    /api/v1/recipes/**,
    /api/v1/meals,
    /api/v1/meals/**

#frontend:
#  address: http://localhost:4200
#
#jwt:
#  secret: ${JWT_SECRET}
#
#ignore:
#  matchers: >
#    /api/v1/user,
#    /api/v1/pantries,
#    /api/v1/pantries/**,
#    /api/v1/products,
#    /api/v1/groups,
#    /api/v1/groups/**,
#    /api/v1/shopping-lists,
#    /api/v1/shopping-lists/**,
#    /api/v1/recipes,
#    /api/v1/recipes/**,
#    /api/v1/meals,
#    /api/v1/meals/**