export enum AuthorityEnum {
  READ = 'READ',
  ADD = 'ADD',
  DELETE = 'DELETE',
  RESERVE = 'RESERVE',
  MODIFY = 'MODIFY',
  MODIFY_PANTRY = 'MODIFY_PANTRY',
  DELETE_PANTRY = 'DELETE_PANTRY',
  MODIFY_GROUP = 'MODIFY_GROUP',
  DELETE_GROUP = 'DELETE_GROUP',
  ADD_TO_GROUP = 'ADD_TO_GROUP',
  DELETE_FROM_GROUP = 'DELETE_FROM_GROUP',
}
