export enum AuthorityEnum {
  ADD = 'ADD',
  RESERVE = 'RESERVE',
  MODIFY = 'MODIFY',
  MODIFY_PANTRY = 'MODIFY_PANTRY',
  MODIFY_GROUP = 'MODIFY_GROUP',
  ADD_TO_GROUP = 'ADD_TO_GROUP',
  CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST',
  MODIFY_SHOPPING_LIST = 'MODIFY_SHOPPING_LIST',
  ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST',
}

export const authorityEnums = [
  AuthorityEnum.ADD,
  AuthorityEnum.RESERVE,
  AuthorityEnum.MODIFY,
  AuthorityEnum.MODIFY_PANTRY,
  AuthorityEnum.MODIFY_GROUP,
  AuthorityEnum.ADD_TO_GROUP,
  AuthorityEnum.CREATE_SHOPPING_LIST,
  AuthorityEnum.MODIFY_SHOPPING_LIST,
  AuthorityEnum.ADD_TO_SHOPPING_LIST,
];
