export enum Category {
  DAIRY = 'DAIRY',
  FRUITS = 'FRUITS',
  VEGETABLES = 'VEGETABLES',
  MEAT = 'MEAT',
  ANIMAL_PRODUCTS = 'ANIMAL_PRODUCTS',
  SPICES = 'SPICES',
  BREAD_AND_BAKERY = 'BREAD_AND_BAKERY',
  TEA = 'TEA',
  COFFEE = 'COFFEE',
  SOFT_DRINKS = 'SOFT_DRINKS',
  ALCOHOL = 'ALCOHOL',
  SEAFOOD = 'SEAFOOD',
  FREEZER = 'FREEZER',
  DRIED_GOODS = 'DRIED_GOODS',
  SNACKS = 'SNACKS',
  SWEETS = 'SWEETS',
  CANNED_GOODS = 'CANNED_GOODS',
  PASTA = 'PASTA',
  RICE = 'RICE',
  CEREAL = 'CEREAL',
  BAKING_GOODS = 'BAKING_GOODS',
}

export const categories = [
  Category.DAIRY,
  Category.FRUITS,
  Category.VEGETABLES,
  Category.MEAT,
  Category.ANIMAL_PRODUCTS,
  Category.SPICES,
  Category.BREAD_AND_BAKERY,
  Category.TEA,
  Category.COFFEE,
  Category.SOFT_DRINKS,
  Category.ALCOHOL,
  Category.SEAFOOD,
  Category.FREEZER,
  Category.DRIED_GOODS,
  Category.SNACKS,
  Category.SWEETS,
  Category.CANNED_GOODS,
  Category.PASTA,
  Category.RICE,
  Category.CEREAL,
  Category.BAKING_GOODS,
];
